### ISSUE TITLE
Ajánlat

### ISSUE THREAD

**Issue by Hubya** [BiaEszterBalazs/beadando#2]
Eszter kérlek készítsd el az ajánlatot.

**Comment by goe9698** [comment]
Elkészítettem az ajánlatkérés elfogadást. 15 perc volt. Nemsokára megcsinálom az ajánlatot is.

**Comment by goe9698** [comment]
Az ajánlat 80 %-ával készen vagyok. Eddig 3 és fél órát töltöttem vele.

**Comment by goe9698** [comment]
Elkészültem az ajánlattal, 5 órára volt szükségem az elkészítés során.
