### ISSUE TITLE
Program

### ISSUE THREAD

**Issue by Hubya** [BiaEszterBalazs/beadando#5]
Lehet készíteni a programot.

**Comment by BalCeBal** [comment]
Elkezdem elkészíteni a programot.
Megcsinálom a grafikus felületet és hozzá néhány funkciót.
Délutánra várható, hogy kész leszek vele.

**Comment by BalCeBal** [comment]
Felkerült a minta verzió.
Amennyiben megfelelőnek találják folytatjuk a fejlesztést.
Üdvözlettel,
Balázs

**Comment by BalCeBal** [comment]
Kedves Bianka
Telefonbeszélgetésünkre hivatkozva, amelyben elfogadta a további fejlesztést feltöltöm a végleges verziót.
A programhoz a dokumentációt a doksi 1.0-ában találja majd.

**Comment by Hubya** [comment]
Kérlek írd le Balázs, hogy az elkészítés mennyi idődbe került.

**Comment by BalCeBal** [comment]
A szoftver elkészítése tizenkét órát vett igénybe.
A módosítási kérelemben igényelt funkciók fejlesztése további öt órát igényeltek.
Összesen tizenhét óra a ráfordított idő.
--Balázs

**Comment by BalCeBal** [comment]
Ha nincs más kérdés lezárom az issuet.
Üdv,
Balázs
